-- Bercut Barber Shop — PostgreSQL Schema
-- Run once on VPS: psql -U postgres -d bercut -f schema.sql
-- All UUIDs generated by gen_random_uuid() (pgcrypto extension)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. BRANCHES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS branches (
  id                                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name                              VARCHAR(100) NOT NULL,
  address                           TEXT,
  city                              VARCHAR(80),
  timezone                          VARCHAR(50)  NOT NULL DEFAULT 'Asia/Makassar',
  tip_distribution_method           VARCHAR(20)  NOT NULL DEFAULT 'individual'
                                      CHECK (tip_distribution_method IN ('individual','equal_split','proportional')),
  pay_period_type                   VARCHAR(10)  NOT NULL DEFAULT 'monthly',
  is_active                         BOOLEAN      NOT NULL DEFAULT true,
  is_head_office                    BOOLEAN      NOT NULL DEFAULT false,
  -- Online booking
  online_booking_slug               VARCHAR(80)  UNIQUE,
  online_booking_enabled            BOOLEAN      NOT NULL DEFAULT true,
  -- Operations config (moved from Settings → Branch Settings)
  speaker_enabled                   BOOLEAN      NOT NULL DEFAULT true,
  web_push_enabled                  BOOLEAN      NOT NULL DEFAULT false,
  late_start_threshold_minutes      SMALLINT     NOT NULL DEFAULT 10,
  ack_grace_period_minutes          SMALLINT     NOT NULL DEFAULT 2,
  auto_cancel_minutes               SMALLINT     NOT NULL DEFAULT 15,
  tip_presets                       JSONB        NOT NULL DEFAULT '[5000,10000,20000,50000,100000]',
  -- Escalation
  barber_escalation_interval_minutes SMALLINT    NOT NULL DEFAULT 3,
  barber_escalation_max_count        SMALLINT    NOT NULL DEFAULT 5,
  -- WhatsApp alerts
  backoffice_alert_phone            VARCHAR(25),
  whatsapp_enabled                  BOOLEAN      NOT NULL DEFAULT true,
  created_at                        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. USERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  email         VARCHAR(200) NOT NULL UNIQUE,
  password_hash TEXT         NOT NULL,
  name          VARCHAR(100) NOT NULL,
  role          VARCHAR(20)  NOT NULL DEFAULT 'manager'
                  CHECK (role IN ('owner','manager','accountant','monitoring')),
  is_active     BOOLEAN      NOT NULL DEFAULT true,
  last_login_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. USER PERMISSIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_permissions (
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  section    VARCHAR(50) NOT NULL,
  is_enabled BOOLEAN     NOT NULL DEFAULT true,
  PRIMARY KEY (user_id, section)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. AUDIT LOG
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID         REFERENCES users(id) ON DELETE SET NULL,
  action      VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50),
  entity_id   UUID,
  diff        JSONB,
  branch_id   UUID         REFERENCES branches(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. BARBERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS barbers (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id       UUID         REFERENCES branches(id) ON DELETE SET NULL,  -- nullable for freelancers
  name            VARCHAR(100) NOT NULL,
  specialty       VARCHAR(100),
  specialty_id    VARCHAR(100),
  phone           VARCHAR(20),
  pin_hash        TEXT,
  status          VARCHAR(20)  NOT NULL DEFAULT 'clocked_out'
                    CHECK (status IN ('available','in_service','on_break','clocked_out','off')),
  commission_rate DECIMAL(5,2) NOT NULL DEFAULT 40.00,   -- fallback rate
  base_salary     INTEGER      NOT NULL DEFAULT 0,
  pay_type        VARCHAR(30)  NOT NULL DEFAULT 'salary_plus_commission'
                    CHECK (pay_type IN ('salary_plus_commission','commission_only','daily_rate')),
  daily_rate      INTEGER      NOT NULL DEFAULT 0,
  avatar_url      TEXT,
  sort_order      SMALLINT     NOT NULL DEFAULT 0,
  is_active       BOOLEAN      NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. SERVICES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name             VARCHAR(100) NOT NULL,
  name_id          VARCHAR(100),
  category         VARCHAR(20)  NOT NULL
                     CHECK (category IN ('haircut','beard','treatment','hair_color','package')),
  base_price       INTEGER      NOT NULL DEFAULT 0,
  duration_minutes SMALLINT     NOT NULL DEFAULT 30,
  badge            VARCHAR(50),
  description      TEXT,
  is_active        BOOLEAN      NOT NULL DEFAULT true,
  sort_order       SMALLINT     NOT NULL DEFAULT 0,
  image_url        TEXT,
  mutex_group      VARCHAR(50),   -- e.g. 'ear_treatment', 'beard_service'
  created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. BRANCH SERVICES (per-branch price + availability + commission rate)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS branch_services (
  service_id      UUID     NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  branch_id       UUID     NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  is_available    BOOLEAN  NOT NULL DEFAULT true,
  price           INTEGER,            -- NULL = use services.base_price
  commission_rate DECIMAL(5,2),       -- NULL = fall back to barbers.commission_rate
  PRIMARY KEY (service_id, branch_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. BARBER SERVICES (capability per barber, global)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS barber_services (
  barber_id  UUID    NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  service_id UUID    NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (barber_id, service_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. INVENTORY ITEMS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_items (
  id        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name      VARCHAR(100) NOT NULL,
  unit      VARCHAR(20)  NOT NULL DEFAULT 'pcs',
  category  VARCHAR(30)  NOT NULL
              CHECK (category IN ('beverage','product','service_consumable')),
  is_active BOOLEAN      NOT NULL DEFAULT true
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. SERVICE CONSUMABLES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS service_consumables (
  service_id  UUID           NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  item_id     UUID           NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  qty_per_use DECIMAL(8,3)   NOT NULL DEFAULT 1,
  PRIMARY KEY (service_id, item_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. CUSTOMERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name                  VARCHAR(100) NOT NULL,
  phone                 VARCHAR(25)  UNIQUE,   -- E.164 format
  phone_country_code    VARCHAR(5),
  total_visits          INTEGER      NOT NULL DEFAULT 0,
  total_spend           INTEGER      NOT NULL DEFAULT 0,
  points_balance        INTEGER      NOT NULL DEFAULT 0,
  preferred_barber_id   UUID         REFERENCES barbers(id) ON DELETE SET NULL,
  first_visit           DATE,
  last_visit            DATE,
  points_last_activity_at TIMESTAMPTZ,
  points_last_expired_at  TIMESTAMPTZ,
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 12. BOOKINGS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bookings (
  id                     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_number         VARCHAR(10)  NOT NULL,
  branch_id              UUID         NOT NULL REFERENCES branches(id),
  barber_id              UUID         NOT NULL REFERENCES barbers(id),
  customer_id            UUID         REFERENCES customers(id) ON DELETE SET NULL,
  guest_name             VARCHAR(100),
  guest_phone            VARCHAR(25),
  scheduled_at           TIMESTAMPTZ  NOT NULL,
  auto_cancel_at         TIMESTAMPTZ,             -- NULL for "Now" bookings
  started_at             TIMESTAMPTZ,
  completed_at           TIMESTAMPTZ,
  paid_at                TIMESTAMPTZ,
  acknowledged_at        TIMESTAMPTZ,
  status                 VARCHAR(20)  NOT NULL DEFAULT 'confirmed'
                           CHECK (status IN ('confirmed','in_progress','pending_payment','completed','no_show','cancelled')),
  payment_status         VARCHAR(10)  NOT NULL DEFAULT 'unpaid'
                           CHECK (payment_status IN ('unpaid','paid','refunded')),
  payment_method         VARCHAR(10)  CHECK (payment_method IN ('qris','card','cash','manual')),
  payment_trigger_source VARCHAR(20),  -- 'barber' | 'admin'
  payment_ref            VARCHAR(100),
  group_id               UUID,        -- FK set after booking_groups is created
  source                 VARCHAR(20)  NOT NULL DEFAULT 'walk_in'
                           CHECK (source IN ('walk_in','any_available','online')),
  points_redeemed        INTEGER      NOT NULL DEFAULT 0,
  points_earned          INTEGER      NOT NULL DEFAULT 0,
  review_tags            TEXT[],
  rating                 SMALLINT,
  cancellation_reason    TEXT,
  notes                  TEXT,
  -- Escalation tracking
  escalation_count       SMALLINT     NOT NULL DEFAULT 0,
  escalation_stopped_at  TIMESTAMPTZ,
  escalation_stopped_by  UUID         REFERENCES users(id) ON DELETE SET NULL,
  escalation_stop_reason VARCHAR(30)  CHECK (escalation_stop_reason IN ('barber_started','admin_cancelled','max_reached','no_show')),
  client_not_arrived_at  TIMESTAMPTZ,
  created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 13. BOOKING SERVICES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS booking_services (
  id              UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id      UUID    NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  service_id      UUID    NOT NULL REFERENCES services(id),
  price_charged   INTEGER NOT NULL,
  added_mid_cut   BOOLEAN NOT NULL DEFAULT false,
  paid_with_points BOOLEAN NOT NULL DEFAULT false,
  bleach_step     SMALLINT,
  bleach_with_color BOOLEAN
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 14. BOOKING EXTRAS (beverages & products ordered at kiosk)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS booking_extras (
  id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id UUID    NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  item_id    UUID    NOT NULL REFERENCES inventory_items(id),
  quantity   INTEGER NOT NULL DEFAULT 1,
  price      INTEGER NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 15. BOOKING GROUPS (group payment)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS booking_groups (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id  UUID        NOT NULL REFERENCES branches(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add FK from bookings → booking_groups after both tables exist
ALTER TABLE bookings
  ADD CONSTRAINT fk_bookings_group_id
  FOREIGN KEY (group_id) REFERENCES booking_groups(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 16. TIPS (individual per barber)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tips (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id     UUID         NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
  barber_id      UUID         NOT NULL REFERENCES barbers(id),
  branch_id      UUID         NOT NULL REFERENCES branches(id),
  amount         INTEGER      NOT NULL,
  payment_method VARCHAR(10),
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 17. POINT TRANSACTIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS point_transactions (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID         NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  booking_id  UUID         REFERENCES bookings(id) ON DELETE SET NULL,
  type        VARCHAR(10)  NOT NULL
                CHECK (type IN ('earn','redeem','expired','adjustment')),
  points      INTEGER      NOT NULL,  -- negative for redeem/expired
  balance_after INTEGER    NOT NULL,
  note        TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 18. EXPENSE CATEGORIES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expense_categories (
  id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  key        VARCHAR(50)  NOT NULL UNIQUE,
  label      VARCHAR(100) NOT NULL,
  color      VARCHAR(7)   NOT NULL DEFAULT '#111110',
  bg         VARCHAR(7)   NOT NULL DEFAULT '#F2F0EB',
  is_active  BOOLEAN      NOT NULL DEFAULT true,
  sort_order SMALLINT     NOT NULL DEFAULT 0
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 19. PURCHASE ORDERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_orders (
  id                  VARCHAR(20)  PRIMARY KEY,   -- e.g. PO-001
  item_id             UUID         NOT NULL REFERENCES inventory_items(id),
  item_name           VARCHAR(100) NOT NULL,
  unit                VARCHAR(20)  NOT NULL,
  status              VARCHAR(10)  NOT NULL DEFAULT 'open'
                        CHECK (status IN ('open','closed')),
  total_order_amount  INTEGER      NOT NULL,
  paid_amount         INTEGER      NOT NULL DEFAULT 0,
  created_date        DATE         NOT NULL,
  closed_date         DATE,
  distributions       JSONB,       -- [{branch_id, branch, qty, cost}]
  created_by          UUID         REFERENCES users(id) ON DELETE SET NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 20. EXPENSES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expenses (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id        UUID         REFERENCES branches(id),  -- nullable for multi-branch PO advances
  submitted_by     UUID         NOT NULL REFERENCES users(id),
  type             VARCHAR(20)  NOT NULL DEFAULT 'regular'
                     CHECK (type IN ('regular','inventory','kasbon')),
  category_id      UUID         REFERENCES expense_categories(id),
  source           VARCHAR(20)  NOT NULL DEFAULT 'petty_cash'
                     CHECK (source IN ('petty_cash','owner')),
  amount           INTEGER      NOT NULL,
  description      TEXT,
  receipt_url      TEXT         NOT NULL,
  has_stock_receipt BOOLEAN     NOT NULL DEFAULT false,
  expense_date     DATE         NOT NULL,
  barber_id        UUID         REFERENCES barbers(id),   -- kasbon only
  deduct_period    VARCHAR(10)  DEFAULT 'current'
                     CHECK (deduct_period IN ('current','next')),  -- kasbon only
  po_id            VARCHAR(20)  REFERENCES purchase_orders(id),
  po_payment_type  VARCHAR(10)  CHECK (po_payment_type IN ('advance','final')),
  po_attribution   JSONB,       -- [{branch_id, branch, amount}]
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 21. EXPENSE STOCK ITEMS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expense_stock_items (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  expense_id        UUID          NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
  item_id           UUID          NOT NULL REFERENCES inventory_items(id),
  branch_id         UUID          NOT NULL REFERENCES branches(id),
  quantity_received DECIMAL(10,3) NOT NULL,
  unit              VARCHAR(20)   NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 22. ATTENDANCE
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS attendance (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  barber_id     UUID         NOT NULL REFERENCES barbers(id),
  branch_id     UUID         NOT NULL REFERENCES branches(id),
  clock_in_at   TIMESTAMPTZ  NOT NULL,
  clock_out_at  TIMESTAMPTZ
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 23. OFF RECORDS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS off_records (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  barber_id       UUID        NOT NULL REFERENCES barbers(id),
  branch_id       UUID        NOT NULL REFERENCES branches(id),
  date            DATE        NOT NULL,
  type            VARCHAR(10) NOT NULL CHECK (type IN ('excused','inexcused')),
  has_doctor_note BOOLEAN     NOT NULL DEFAULT false,
  note            TEXT,
  logged_by       UUID        REFERENCES users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 24. INVENTORY STOCK (per-branch)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_stock (
  item_id           UUID    NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  branch_id         UUID    NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  current_stock     INTEGER NOT NULL DEFAULT 0,
  reorder_threshold INTEGER NOT NULL DEFAULT 5,
  price             INTEGER,   -- selling price; NULL for service_consumables
  kiosk_visible     BOOLEAN NOT NULL DEFAULT true,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (item_id, branch_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 25. INVENTORY MOVEMENTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_movements (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id       UUID        NOT NULL REFERENCES inventory_items(id),
  branch_id     UUID        NOT NULL REFERENCES branches(id),
  logged_by     UUID        REFERENCES users(id) ON DELETE SET NULL,
  movement_type VARCHAR(5)  NOT NULL CHECK (movement_type IN ('in','out')),
  quantity      DECIMAL(10,3) NOT NULL,
  note          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 26. CHAIRS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chairs (
  id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id  UUID         NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  label      VARCHAR(30)  NOT NULL,   -- e.g. "Chair 1", "Kursi A"
  barber_id  UUID         REFERENCES barbers(id) ON DELETE SET NULL,  -- permanent default
  sort_order SMALLINT     NOT NULL DEFAULT 0
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 27. CHAIR OVERRIDES (temporary/indefinite coverage)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chair_overrides (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  chair_id    UUID        NOT NULL REFERENCES chairs(id) ON DELETE CASCADE,
  barber_id   UUID        NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  date_from   DATE        NOT NULL,
  date_to     DATE,       -- NULL = indefinite
  reason      TEXT,
  created_by  UUID        REFERENCES users(id) ON DELETE SET NULL,
  resolved_by UUID        REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 28. BARBER BREAKS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS barber_breaks (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  barber_id   UUID         NOT NULL REFERENCES barbers(id),
  branch_id   UUID         NOT NULL REFERENCES branches(id),
  started_at  TIMESTAMPTZ  NOT NULL,
  ended_at    TIMESTAMPTZ,
  duration_minutes SMALLINT,   -- requested duration (15/30/45)
  reason      VARCHAR(30)  DEFAULT 'lunch'
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 29. PACKAGE SERVICES (junction table for services included in a package)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS package_services (
  package_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  service_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  PRIMARY KEY (package_id, service_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 30. FEEDBACK TAGS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_tags (
  id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  label      VARCHAR(80)  NOT NULL,
  context    VARCHAR(10)  NOT NULL CHECK (context IN ('good','bad','neutral')),
  sort_order SMALLINT     NOT NULL DEFAULT 0,
  is_active  BOOLEAN      NOT NULL DEFAULT true
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 30. PAYROLL SETTINGS (global singleton)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payroll_settings (
  id                               UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
  late_deduction_per_minute        INTEGER  NOT NULL DEFAULT 2000,
  late_grace_period_minutes        SMALLINT NOT NULL DEFAULT 5,
  inexcused_off_flat_deduction     INTEGER  NOT NULL DEFAULT 150000,
  excused_off_flat_deduction       INTEGER  NOT NULL DEFAULT 150000,
  off_quota_per_month              SMALLINT NOT NULL DEFAULT 4,
  -- Overtime commission
  ot_commission_enabled            BOOLEAN  NOT NULL DEFAULT false,
  ot_threshold_time                TIME     NOT NULL DEFAULT '19:00',
  ot_bonus_pct                     DECIMAL(4,2) NOT NULL DEFAULT 5.00,
  ot_excluded_service_ids          UUID[]   NOT NULL DEFAULT '{}',
  -- Working days
  working_days_per_week            DECIMAL(3,1) NOT NULL DEFAULT 6.0
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 31. PAYROLL PERIODS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payroll_periods (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id         UUID        REFERENCES branches(id),  -- NULL = all branches
  period_month      VARCHAR(7)  NOT NULL,    -- "2026-04" (start month)
  period_from       DATE        NOT NULL,    -- 16th of start month
  period_to         DATE        NOT NULL,    -- 15th of next month
  status            VARCHAR(15) NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','reviewed','communicated')),
  generated_by      UUID        REFERENCES users(id) ON DELETE SET NULL,
  communicated_by   UUID        REFERENCES users(id) ON DELETE SET NULL,
  communicated_at   TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 32. PAYROLL ENTRIES (one per barber per period)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payroll_entries (
  id                          UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
  period_id                   UUID     NOT NULL REFERENCES payroll_periods(id) ON DELETE CASCADE,
  barber_id                   UUID     NOT NULL REFERENCES barbers(id),
  branch_id                   UUID     NOT NULL REFERENCES branches(id),
  pay_type                    VARCHAR(30) NOT NULL,
  -- Earnings
  base_salary                 INTEGER  NOT NULL DEFAULT 0,
  gross_service_revenue       INTEGER  NOT NULL DEFAULT 0,
  commission_regular          INTEGER  NOT NULL DEFAULT 0,
  commission_ot               INTEGER  NOT NULL DEFAULT 0,
  total_tips                  INTEGER  NOT NULL DEFAULT 0,
  -- Attendance counts
  total_late_minutes          INTEGER  NOT NULL DEFAULT 0,
  inexcused_fixed_days        INTEGER  NOT NULL DEFAULT 0,
  inexcused_prorata_days      INTEGER  NOT NULL DEFAULT 0,
  excused_fixed_days          INTEGER  NOT NULL DEFAULT 0,
  excused_prorata_days        INTEGER  NOT NULL DEFAULT 0,
  working_days                INTEGER  NOT NULL DEFAULT 26,  -- computed, admin-editable
  -- Deductions (auto-calculated, override possible)
  late_deduction              INTEGER  NOT NULL DEFAULT 0,
  inexcused_off_deduction     INTEGER  NOT NULL DEFAULT 0,
  excused_off_deduction       INTEGER  NOT NULL DEFAULT 0,
  kasbon_total                INTEGER  NOT NULL DEFAULT 0,   -- auto-imported from expenses
  -- Net
  net_pay                     INTEGER  NOT NULL DEFAULT 0,
  UNIQUE (period_id, barber_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 33. PAYROLL ADJUSTMENTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payroll_adjustments (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  payroll_entry_id UUID       NOT NULL REFERENCES payroll_entries(id) ON DELETE CASCADE,
  type            VARCHAR(10) NOT NULL CHECK (type IN ('addition','deduction')),
  category        VARCHAR(60) NOT NULL,
  remarks         TEXT,
  amount          INTEGER     NOT NULL,
  by              UUID        REFERENCES users(id) ON DELETE SET NULL,
  date            DATE,
  is_kasbon       BOOLEAN     NOT NULL DEFAULT false,
  expense_id      UUID        REFERENCES expenses(id) ON DELETE SET NULL,
  deduct_period   VARCHAR(10) DEFAULT 'current' CHECK (deduct_period IN ('current','next'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 34. PAX OUT EVENTS (idle timeout / back-press analytics)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pax_out_events (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id  UUID        NOT NULL REFERENCES branches(id),
  step       SMALLINT    NOT NULL,
  step_label VARCHAR(50),
  source     VARCHAR(30) NOT NULL,  -- 'kiosk_timeout' | 'kiosk_back' | 'cctv_manual'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 35. KIOSK SETTINGS (per-branch, can be null = use defaults)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kiosk_settings (
  branch_id             UUID    PRIMARY KEY REFERENCES branches(id) ON DELETE CASCADE,
  welcome_cta           VARCHAR(100),
  welcome_cta_id        VARCHAR(100),
  welcome_subtitle      VARCHAR(200),
  welcome_subtitle_id   VARCHAR(200),
  upsell_enabled        BOOLEAN NOT NULL DEFAULT true,
  upsell_heading        VARCHAR(100),
  upsell_heading_id     VARCHAR(100),
  upsell_switch_cta     VARCHAR(80),
  upsell_keep_cta       VARCHAR(100),
  upsell_rules          JSONB,
  suggest_services      JSONB,
  category_order        JSONB,
  svc_order_by_cat      JSONB,
  service_visible       JSONB,
  session_timeout_secs  SMALLINT NOT NULL DEFAULT 60,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 36. KIOSK TOKENS (device auth)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kiosk_tokens (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id    UUID         NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  token_hash   VARCHAR(64)  NOT NULL UNIQUE,  -- SHA-256 of the raw token
  device_name  VARCHAR(100) NOT NULL DEFAULT 'Kiosk',
  is_active    BOOLEAN      NOT NULL DEFAULT true,
  last_seen_at TIMESTAMPTZ,
  created_by   UUID         REFERENCES users(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 37. WHATSAPP SETTINGS (global singleton)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS whatsapp_settings (
  id                          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  provider                    VARCHAR(20) NOT NULL DEFAULT 'fonnte'
                                CHECK (provider IN ('fonnte','whatsapp_business_api')),
  fonnte_api_key              TEXT,
  fonnte_sender               VARCHAR(25),
  wa_phone_number_id          TEXT,
  wa_access_token             TEXT,
  is_enabled                  BOOLEAN NOT NULL DEFAULT false,
  -- Templates
  template_booking_confirmation TEXT,
  template_queue_number         TEXT,
  template_receipt              TEXT,
  template_barber_new_booking   TEXT,
  template_barber_escalation    TEXT,
  template_late_customer_reminder TEXT,
  template_client_not_arrived   TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 38. GLOBAL SETTINGS (loyalty + other global config)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS global_settings (
  id                         UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Loyalty
  points_earn_rate           DECIMAL(8,4) NOT NULL DEFAULT 0.0001,  -- 1 point per Rp 10,000
  points_redemption_rate     INTEGER      NOT NULL DEFAULT 10000,    -- 1 point = Rp 10,000
  points_expiry_months       SMALLINT     NOT NULL DEFAULT 12,       -- 0 = never expire
  points_expiry_warning_days SMALLINT     NOT NULL DEFAULT 30
);

-- ─────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_bookings_branch_status        ON bookings(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_bookings_barber_scheduled     ON bookings(barber_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_bookings_branch_date          ON bookings(branch_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_bookings_customer             ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_booking_services_booking      ON booking_services(booking_id);
CREATE INDEX IF NOT EXISTS idx_attendance_barber_date        ON attendance(barber_id, clock_in_at);
CREATE INDEX IF NOT EXISTS idx_attendance_branch_date        ON attendance(branch_id, clock_in_at);
CREATE INDEX IF NOT EXISTS idx_expenses_branch_date          ON expenses(branch_id, expense_date);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_branch    ON inventory_movements(branch_id, created_at);
CREATE INDEX IF NOT EXISTS idx_point_transactions_customer   ON point_transactions(customer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_created             ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_off_records_barber_date       ON off_records(barber_id, date);
CREATE INDEX IF NOT EXISTS idx_chair_overrides_chair_date    ON chair_overrides(chair_id, date_from, date_to);
CREATE INDEX IF NOT EXISTS idx_payroll_entries_period        ON payroll_entries(period_id);
CREATE INDEX IF NOT EXISTS idx_customers_phone               ON customers(phone);
